default_agent: ai_service
agents:
  ai_service:
    name: ai_service
    entrypoint: C:/FromProm/FromProm/service/ai-service/agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\FromProm\FromProm\service\ai-service
    aws:
      execution_role: arn:aws:iam::261595668962:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-ec40b9ec00
      execution_role_auto_create: false
      account: '261595668962'
      region: us-east-1
      ecr_repository: 261595668962.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-ai_service
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: ai_service-IiSUYrFdjB
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:261595668962:runtime/ai_service-IiSUYrFdjB
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-ai_service-builder
      execution_role: arn:aws:iam::261595668962:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-ec40b9ec00
      source_bucket: bedrock-agentcore-codebuild-sources-261595668962-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: ai_service_mem-Lnw5H3Docx
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:261595668962:memory/ai_service_mem-Lnw5H3Docx
      memory_name: ai_service_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
