apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      serviceAccountName: auth-service-sa
      containers:
      - name: auth-service
        image: 261595668962.dkr.ecr.ap-northeast-2.amazonaws.com/fromprom/auth:afedf075
        ports:
        - containerPort: 33000
        env:
        # Spring Boot 3.x 규칙: aws.credentials.accessKey -> AWS_CREDENTIALS_ACCESSKEY
        - name: AWS_CREDENTIALS_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: aws-access-key
        - name: AWS_CREDENTIALS_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: aws-secret-key
# 2. Cognito (에러 발생 중인 부분 수정)
        - name: AWS_COGNITO_CLIENTID  # AWS_COGNITO_CLIENT_ID에서 언더바 제거
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: cognito-client-id
        - name: AWS_COGNITO_USERPOOLID # AWS_COGNITO_USER_POOL_ID에서 언더바 제거
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: cognito-user-pool-id

        # 3. SNS & DynamoDB & Region
        - name: AWS_SNS_TOPIC_ARN
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: sns-topic-arn
        - name: AWS_DYNAMODB_TABLE_NAME
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: dynamodb-table-name
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: aws-region
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthy
            port: 33000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthy
            port: 33000
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 33000
    targetPort: 33000
  type: ClusterIP