apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: fromprom
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      serviceAccountName: fromprom-sa
      containers:
        - name: auth-service
          image: fromprom/auth:latest
          ports:
            - containerPort: 33000
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
          envFrom:
            - secretRef:
                name: aws-credentials
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthy
              port: 33000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthy
              port: 33000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: fromprom
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 33000
      targetPort: 33000
      protocol: TCP
