apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      serviceAccountName: auth-service-sa
      containers:
      - name: auth-service
        image: 261595668962.dkr.ecr.ap-northeast-2.amazonaws.com/fromprom/auth:56bfb78c
        ports:
        # [수정] 컨테이너 내부 실제 포트인 8080으로 변경
        - containerPort: 8080 
        env:
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: AWS_COGNITO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: cognito-client-id
        - name: AWS_COGNITO_USER_POOL_ID
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: cognito-user-pool-id
        - name: AWS_SNS_TOPIC_ARN
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: sns-topic-arn
        - name: AWS_DYNAMODB_TABLE_NAME
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: dynamodb-table-name
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthy
            # [수정] 앱이 떠 있는 8080 포트로 헬스체크 수행
            port: 8080 
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthy
            # [수정] 앱이 떠 있는 8080 포트로 준비상태 확인
            port: 8080 
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 33000          # 외부/다른 서비스에서 접속할 포트 (유지)
    # [수정] 서비스가 받은 신호를 전달할 실제 타겟 포트 (8080으로 변경)
    targetPort: 8080 
  type: ClusterIP